version: '3.4'

services:

  mongodb-cube:
    container_name: mongodb-cube
    restart: always
    volumes:
    - ${WEBAPP_STORAGE_HOME}/site:/data/db
    ports:
    - "27017:27017"

  sm.emoticubo.web:
    container_name: sm.emoticubo.web
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "AppSettings__MongoDbUrl=mongodb://mongodb-cube:27017"
    depends_on:
    - mongodb-cube
    ports:
      - "8089:80"
